// <auto-generated />
using System;
using AesCloudDataNet.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AesCloudDataNet.Migrations
{
    [DbContext(typeof(AesCloudDataContext))]
    [Migration("20210423185219_ITINIAL")]
    partial class ITINIAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("AesCloudDataNet.Models.RateToUsd", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(767)");

                    b.Property<double>("Ask")
                        .HasColumnType("double");

                    b.Property<double>("Bid")
                        .HasColumnType("double");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<DateTime>("Stored")
                        .HasColumnType("datetime");

                    b.HasKey("Code");

                    b.ToTable("RateToUsd");
                });

            modelBuilder.Entity("AesCloudDataNet.Models.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte[]>("Guid")
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AesCloudDataNet.Models.UserAction", b =>
                {
                    b.Property<int>("UserActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Blob")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("Guid")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Json")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PriodSec")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("UserActionId");

                    b.ToTable("UserActions");
                });
#pragma warning restore 612, 618
        }
    }
}
